config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #homes
  root to: 'homes#top'
  get "home/about" => "homes#about"

  #users(relationships,rate_graph_comments,favoritesネスト)
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :rate_graph_comments, only: [:create, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    post '/' => 'users#create', as: 'comments'
    delete '/' => 'users#destroy', as: 'comment'
  end

  #rate_graphs
  resources :rate_graphs, only: [:index, :create, :edit, :update]

  #search
  get '/search', to: 'searches#search'

end

app/models/rate_graph.rb
class RateGraph < ApplicationRecord

  #ユーザーとのリレーション
  belongs_to :user


  #試合前レート、試合後レートのバリデーション
  validates :before_rate, presence: true, numericality: { only_integer: true }
  validates :after_rate, presence: true, numericality: { only_integer: true }

  #グラフ
  def self.chart_date
    pluck('id', 'after_rate').to_h
  end
end

app/controllers/rate_graphs_controller.rb
class RateGraphsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @rate_graphs = Kaminari.paginate_array(current_user.rate_graphs).page(params[:page])
  end

  def create
    @rate_graph = RateGraph.new(rate_graph_params)
    @rate_graph.user_id = current_user.id
    if @rate_graph.save
      redirect_to user_path(current_user), notice: "正常に入力されました。"
    else
      @rate_graphs = Kaminari.paginate_array(current_user.rate_graphs).page(params[:page])
      render 'index'
    end
  end

  def edit
  end

  def update
    if @rate_graph.update(rate_graph_params)
      redirect_to user_path(current_user), notice: "変更が更新されました。"
    else
      render "edit"
    end
  end

  private

  def rate_graph_params
    params.require(:rate_graph).permit(:before_rate, :after_rate)
  end

  def ensure_correct_user
    @rate_graph = RateGraph.find(params[:id])
    unless @rate_graph.user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/rate_graphs_helper.rb
module RateGraphsHelper
end

app/views/rate_graphs/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h4>
        <span class="text-white bg-secondary font-weight-bold">レート編集</span>
      </h4>
      <!--エラーメッセージ&編集フォーム-->
      <%= form_with model:@rate_graph, local:true do |f| %>
        <span class="text-danger">
          <% if @rate_graph.errors.any? %>
            <%= @rate_graph.errors.count %>errors prohibited this obj from being saved:
              <ul><%= @rate_graph.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              </ul>
            <% end %>
          <% end %>
        </span>
        <div class="form-group font-weight-bold">
          <%= f.label :before_rate, "試合前レート" %>
          <%= f.number_field :before_rate, autofocus:true, min: 0, max: 9999, required:"required", id:"inputBeforeRate" %>
        </div>
        <div class="form-group font-weight-bold">
          <%= f.label :after_rate, "試合後レート"%>
          <%= f.number_field :after_rate, autofocus:true, min: 0, max: 9999, required:"required", id:"inputAfterRate" %>
        </div>
        <div class="form-group">
          <%= f.submit "変更を保存", class: 'btn btn-success' %>
        </div>
      <% end %>
      <%= link_to "戻る", rate_graphs_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/rate_graphs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 offset-md-1">
      <h4>
        <span class="text-white bg-secondary font-weight-bold">レート変動一覧</span>
      </h4>
      <!--一覧表-->
      <% unless @rate_graphs.count == 0 %>
        <table class='table table-hover table-inverse'>
          <thead class="text-white bg-secondary">
            <th class="text-center">試合No.</th>
            <th class="text-center">試合日時</th>
            <th class="text-center">試合前</th>
            <th class="text-center">試合後</th>
            <th class="text-center"></th>
          </thead>
          <tbody>
            <% @rate_graphs.each_with_index do |rate_graph,number| %>
            <tr>
              <td class="text-center"><%= number+1 %></td>
              <td class="text-center font-weight-bold"><%= rate_graph.created_at.strftime("%Y/%m/%d %H:%M") %></td>
              <td class="text-center font-weight-bold"><%= rate_graph.before_rate %></td>
              <td class="text-center font-weight-bold"><%= rate_graph.after_rate %></td>
              <td class="text-center"><%= link_to "編集する", edit_rate_graph_path(rate_graph), class: "btn btn-success" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @rate_graphs %>
      <% else %>
        <p class="text-center font-weight-bold">データがありません。</p>
      <% end %>
    </div>
  </div>
</div>