config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #homes
  root to: 'homes#top'
  get "home/about" => "homes#about"

  #users(relationships,rate_graph_comments,favoritesネスト)
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :rate_graph_comments, only: [:create, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    post '/' => 'users#create', as: 'comments'
    delete '/' => 'users#destroy', as: 'comment'
  end

  #rate_graphs
  resources :rate_graphs, only: [:index, :create, :edit, :update]

  #search
  get '/search', to: 'searches#search'

end

app/models/rate_graph_comment.rb
class RateGraphComment < ApplicationRecord
  #ユーザーとのリレーション
  belongs_to :user
  #いいねとのリレーション
  has_many :favorites

  #バリデーション
  validates :comment, presence: true

  def favorited_by?(current_user)
    favorites.where(user_id: current_user.id).exists?
  end
end

app/controllers/rate_graph_comments_controller.rb
class RateGraphCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    @rate_graph_comment = RateGraphComment.new(rate_graph_comment_params)
    @rate_graph_comment.user_id = current_user.id
    @rate_graph_comment.other_user_id = @user.id
    @rate_graph_comments = RateGraphComment.where(other_user_id: @user.id).order('updated_at DESC').page(params[:page]).per(5)
    unless @rate_graph_comment.save
      render 'error'
    end

  end

  def destroy
    @user = User.find(params[:user_id])
    rate_graph_comment = RateGraphComment.find(params[:id])
    rate_graph_comment.destroy
    @rate_graph_comments = RateGraphComment.where(other_user_id: @user.id).order('updated_at DESC').page(params[:page]).per(5)
  end

  private

  def rate_graph_comment_params
    params.require(:rate_graph_comment).permit(:comment)
  end
end

app/helpers/rate_graph_comments_helper.rb
module RateGraphCommentsHelper
end

app/views/rate_graph_comments/_index.html.erb
<% rate_graph_comments.each do |rate_graph_comment| %>
  <% rate_graph_comment_user = rate_graph_comment.user %>
  <tr>
  	<td>
  	  <!--ユーザー画像＆名前-->
  		<%= link_to user_path(rate_graph_comment_user), class: "user_#{rate_graph_comment_user.id}" do %>
  		  <% if rate_graph_comment.user.image.attached? %>
          <%= image_tag rate_graph_comment.user.image.variant(resize:"50x50") %>
        <% else %>
          <%= image_tag 'PF-noimagemini.png' %>
        <% end %><br>
    		<%= rate_graph_comment_user.name %>
  		<% end %>
  	</td>
  	<!--コメント内容-->
  	<td><%= rate_graph_comment.comment %></td>
  	<!--いいね-->
  	<td id="favorite_<%= rate_graph_comment.id %>"><%= render 'favorites/favorite-btn', user: @user, rate_graph_comment: rate_graph_comment %></td>
  	<% if current_user == rate_graph_comment_user %>
    	<td><%= link_to '削除', user_rate_graph_comment_path(@user.id, rate_graph_comment.id), class: 'btn-sm btn-danger', method: :delete, remote: true %></td>
    <% else %>
      <td></td>
  	<% end %>
  	<td><%= rate_graph_comment.created_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
  </tr>
<% end %>

app/views/rate_graph_comments/create.js.erb
$("#rate_graph_comments_<%= @user.id %>").html("<%= j(render 'rate_graph_comments/index', user: @user) %>");
$("#rate_graph_comment_comment").val("");

app/views/rate_graph_comments/destroy.js.erb
$("#comments_<%= @user.id %>").html("<%= j(render 'users/comments', user: @user, rate_graph_comments: @rate_graph_comments) %>");
$("#rate_graph_comment_comment").val("");

app/views/rate_graph_comments/error.js.erb
$("main > .container").prepend("<%= j(render 'layouts/errors', obj: @rate_graph_comment) %>");