config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #homes
  root to: 'homes#top'
  get "home/about" => "homes#about"

  #users(relationships,rate_graph_comments,favoritesネスト)
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :rate_graph_comments, only: [:create, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    post '/' => 'users#create', as: 'comments'
    delete '/' => 'users#destroy', as: 'comment'
  end

  #rate_graphs
  resources :rate_graphs, only: [:index, :create, :edit, :update]

  #search
  get '/search', to: 'searches#search'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #レートグラフとのリレーション
  has_many :rate_graphs
    #いいね・レートグラフコメントとのリレーション
    has_many :favorites, dependent: :destroy
    has_many :rate_graph_comments, dependent: :destroy

  #ActiveStorage
  has_one_attached :image
  validate :image_type

  #ユーザー名バリデーション
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  #フォローするアクション
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  #フォロー外すアクション
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  #含まれているかどうか（フォローしているか）
  def following?(user)
    followings.include?(user)
  end

  #完全一致, 前方一致, 後方一致, 部分一致の検索手法
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  private
  #画像バリデーション
  def image_type

    unless image.attached?
      return
    end

    if !image.blob.content_type.in?(%('image/jpeg image/png image/jpg'))
      image.purge
      errors.add(:image, 'はJPEGまたはPNG、JPG形式を選択してアップロードしてください')
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @users = User.page(params[:page]).reverse_order
  end

  def show
    @user = User.find(params[:id])
    @rate_graphs = @user.rate_graphs.map.with_index{|rg, idx| [idx+1, rg.after_rate]}
    @rate_graph = RateGraph.new
    @rate_graph_comment = RateGraphComment.new
    @rate_graph_comment.user = @user
    @rate_graph_comments = RateGraphComment.where(other_user_id: @user.id).order('updated_at DESC').page(params[:page]).per(5)
    @page = params[:page]

  end

   def create
    @user = User.find(params[:user_id])
    @rate_graph_comment = RateGraphComment.new(rate_graph_comment_params)
    @rate_graph_comment.user_id = current_user.id
    @rate_graph_comment.other_user_id = @user.id
    @rate_graph_comments = RateGraphComment.where(other_user_id: @user.id).order('updated_at DESC').page(params[:page]).per(5)
    unless @rate_graph_comment.save
      render 'error'
    end
   end

   def destroy
    @user = User.find(params[:user_id])
    @rate_graph_comments = RateGraphComment.where(other_user_id: @user.id).order('updated_at DESC').page(params[:page]).per(5)
    rate_graph_comment = RateGraphComment.where(other_user_id: @user.id).find(params[:id])
    rate_graph_comment.destroy
   end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "変更が更新されました。"
    else
      render :edit
    end
  end

  private


  def rate_graph_comment_params
    params.require(:rate_graph_comment).permit(:comment)
  end

  def user_params
    params.require(:user).permit(:name, :image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_comments.html.erb
<table id="rate_graph_comments_<%= user.id %>">
    <%= render 'rate_graph_comments/index', user: user, rate_graph_comments: rate_graph_comments %>
</table>
<%= paginate rate_graph_comments, remote: true %>

app/views/users/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead class="text-white bg-secondary">
    <th class="text-center"></th>
    <th class="text-center">ユーザー名</th>
    <th class="text-center">フォロー</th>
    <th class="text-center">フォロワー</th>
    <th class="text-center" colspan="3"></th>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td class="text-center">
          <% if user.image.attached? %>
            <%= image_tag user.image.variant(resize:"50x50") %>
          <% else %>
            <%= image_tag 'PF-noimagemini.png' %>
          <% end %>
        </td>
        <td class="text-center font-weight-bold"><%= user.name %></td>
        <td class="text-center font-weight-bold"><%= user.followings.count %>フォロー</td>
        <td class="text-center font-weight-bold"><%= user.followers.count %>フォロワー</td>
        <td class="text-center">
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: 'btn btn-danger'%>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: 'btn btn-info'%>
            <% end %>
          <% end %>
        </td>
        <td class="text-center"><%= link_to 'グラフを見る', user_path(user) %></td></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate users %>

app/views/users/_profile.html.erb
<table class="table">
  <tr>
    <% if @user.image.attached? %>
      <%= image_tag @user.image.variant(resize:"100x100") %>
    <% else %>
      <%= image_tag 'PF-noimage.png' %>
    <% end %>
  </tr>
  <tr>
    <th>ユーザー名 :</th>
    <th>
      <b><%= user.name %></b>
    </th>
  </tr>
  <tr>
    <th>フォロー :</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>フォロワー :</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class="row">
  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-info" %>
    <% end%>
  <% else %>
    <%= link_to "プロフィール編集", edit_user_path(user), class: "btn btn-outline-secondary fas fa-user-cog" %>
  <% end %>
</div>

app/views/users/create.js.erb
$("#comments_<%= @user.id %>").html("<%= j(render 'users/comments', user: @user, rate_graph_comments: @rate_graph_comments) %>");
$("#rate_graph_comment_comment").val("");

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h4>
        <span class="text-white bg-secondary font-weight-bold">プロフィール編集</span>
      </h4>
      <!--エラーメッセージ&編集フォーム-->
      <%= form_with model:@user, local:true do |f| %>
        <span class="text-danger">
          <% if @user.errors.any? %>
            <%= @user.errors.count %>errors prohibited this obj from being saved:
              <ul><%= @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              </ul>
            <% end %>
          <% end %>
        </span>
        <div class="form-group font-weight-bold">
          <%= f.label :image, "プロフィール画像 :" %>
          <%= f.file_field :image, placeholder: "プロフィール画像" %>
        </div>
        <div class="form-group font-weight-bold">
          <%= f.label :name, "ユーザー名 :" %>
          <%= f.text_field :name, autofocus:true, id:"inputName" %>
        </div>
        <div class="form-group">
          <%= f.submit "変更を保存", class: 'btn btn-success' %>
        </div>
      <% end %>
      <%= link_to "戻る", user_path(@user), class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class='mx-auto'>
      <h4>
        <span class="text-white bg-secondary font-weight-bold">ユーザー一覧</span>
      </h4>
      <!--ユーザー一覧-->
      <%= render 'index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <!--current_userと他のユーザーで分岐-->
      <% if current_user != @user %>
        <h4>
          <span class="text-white bg-secondary font-weight-bold"><%= @user.name %>さんのプロフィール</span>
        </h4>
      <% else %>
        <h4>
          <span class="text-white bg-secondary font-weight-bold">マイページ</span>
        </h4>
      <% end %>
      <!--プロフィール-->
      <%= render 'profile', user: @user %>
    </div>
    <div class="col-md-9">
      <!--グラフ表示-->
      <p class="text-danger small">※試合数が少ない段階だと小数点が表示されてしまいますが仕様によるものなのでご了承ください。</p>
      <%= line_chart @rate_graphs, xtitle: "試合数", ytitle: "レート", width: "550px", height: "300px", curve: false, empty: "データがありません。データを追加することで表示されます。" %>

      <% if current_user != @user %>
        <!--マイページではないため表示するものは無し-->
      <% else %>
      <!--エラーメッセージ-->
        <% if @rate_graph.errors.any? %>
            <%= @rate_graph.errors.count %>errors prohibited this obj from being saved:
              <ul><%= @rate_graph.errors.full_massages.each do |message| %>
                <li><%= message %></li>
              </ul>
            <% end %>
        <% end %>
        <!--データ入力フォーム-->
        <%= form_with model: @rate_graph, url: rate_graphs_path, method: :post, local:true do |f| %>
          <span class="text-white bg-secondary fas fa-chart-line">
            レート入力フォーム
          </span>
          <div class="form-group">
            <span class="text-secondary small font-weight-bold">
              <%= f.label :before_rate, "試合前レート:" %>
            </span>
              <%= f.number_field :before_rate, min: 0, max: 9999,placeholder: "0~9999" %>
            <span class="text-secondary small font-weight-bold">
              <%= f.label :after_rate, "試合後レート:" %>
            </span>
              <%= f.number_field :after_rate, min: 0, max: 9999,placeholder: "0~9999" %>
           <!--ボタン-->
              <%= f.submit "データ追加", class: 'btn btn-success' %>
         </div>
        <% end %>
        <!--レート変動一覧　リンク-->
        <u>データを編集したい場合は、 <%= link_to "レート変動一覧", rate_graphs_path %>  から編集してください。</u>
      <% end %>
      <!--コメント表-->
      <div>
        <span class="text-white bg-secondary fas fa-comment">コメント</span>
        <div id="comments_<%= @user.id %>">
          <%= render 'comments', user: @user, rate_graph_comments: @rate_graph_comments %>
        </div>
      </div>

      <!--コメントフォーム-->
      <%= form_with model:[@rate_graph_comment], url: user_comments_path(@user) do |f| %>
        <%= f.text_area :comment,placeholder: "コメントを入力", size:"60x5" %>
        <%= f.submit '送信'%>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.js.erb
$("#comments_<%= @user.id %>").html("<%= j(render 'comments', user: @user, rate_graph_comments: @rate_graph_comments) %>");