config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #homes
  root to: 'homes#top'
  get "home/about" => "homes#about"

  #users(relationships,rate_graph_comments,favoritesネスト)
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :rate_graph_comments, only: [:create, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    post '/' => 'users#create', as: 'comments'
    delete '/' => 'users#destroy', as: 'comment'
  end

  #rate_graphs
  resources :rate_graphs, only: [:index, :create, :edit, :update]

  #search
  get '/search', to: 'searches#search'

end

app/views/layouts/_errors.html.erb
<span class="text-danger">
  <% if obj.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
      <ul>
        <% obj.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</span>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>~efbRateRecorder~</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#0000cd">
    <div class="container">
      <a class="navbar-brand" href="/"><span class="font-weight-bold text-warning">efbRateRecorder</span></a>
      <% if user_signed_in? %>
        <span class="small text-warning font-weight-bold">ようこそ、<%= current_user.name %>さん！</span>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        　<!--ログインしているとき-->
          <li><%= link_to 'マイページ',user_path(current_user), class: 'fas fa-users nav-link text-warning' %></li>
          <li><%= link_to 'ユーザー一覧', users_path, class: 'fas fa-users nav-link text-warning' %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-warning' %></li>
        <% else %>
        　<!--ログインしていないとき-->
          <li><%= link_to 'About', home_about_path, class: 'fas fa-link nav-link text-warning' %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class: 'fas fas fa-user-plus nav-link text-warning' %></li>
          <li><%= link_to 'ログイン', new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-warning' %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<div class="search-form">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content, placeholder: "ユーザー名" %>
    <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
    <%= f.submit '検索' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>efbRateRecorder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <!--検索フォーム-->
      <div class="text-right">
        <% if user_signed_in? %>
          <%= render 'layouts/search' %>
        <% end %>
      </div>

      <p id="notice" class="text-success"><%= notice %></p>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>